"""
Week 7 — Quiz API (provided). You do NOT edit this file.

This module adds the quiz page and a small JSON API to your EXISTING app,
without touching any of your other routes. It is packaged as a Flask
"Blueprint" (a reusable group of routes).

HOW TO USE IT (only two lines added to your own app.py):

    from quiz_api import init_quiz      # 1) import
    init_quiz(app)                      # 2) call it, right after app = Flask(__name__)

That's it — all your existing routes (home, history pages, profile, …) stay as they are.

The routes this adds:
    GET /live-quiz            -> the quiz page (templates/live_quiz.html)
    GET /api/questions/count  -> { "count": 8 }
    GET /api/question/<i>     -> one question as JSON (0-based; 404 if out of range)

The questions are stored in a database. Fill the database once by running:
    python seed_db.py
(Server-side code and databases are taught in later sessions — treat this as a black box.)
"""

import os
import json
from flask import Blueprint, render_template, jsonify, abort
from flask_sqlalchemy import SQLAlchemy

# Shared database instance (also imported by seed_db.py).
db = SQLAlchemy()


class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.Text, nullable=False)
    choices = db.Column(db.Text, nullable=False)       # JSON-encoded list of strings
    answer = db.Column(db.Integer, nullable=False)     # index of the correct choice
    explanation = db.Column(db.Text, nullable=False)


# The group of quiz routes.
quiz_bp = Blueprint("quiz", __name__)


@quiz_bp.route("/live-quiz")
def quiz_page():
    return render_template("live_quiz.html")


@quiz_bp.route("/api/questions/count")
def questions_count():
    return jsonify({"count": Question.query.count()})


@quiz_bp.route("/api/question/<int:index>")
def question(index):
    # index is 0-based: 0 is the first question.
    q = Question.query.order_by(Question.id).offset(index).first()
    if q is None:
        abort(404)
    return jsonify(
        {
            "index": index,
            "question": q.question,
            "choices": json.loads(q.choices),
            "answer": q.answer,
            "explanation": q.explanation,
        }
    )


def database_uri():
    """
    Where the data lives.
    - On Render: the PostgreSQL database (DATABASE_URL environment variable).
    - On your computer (no DATABASE_URL): a local SQLite file 'quiz.db' in your
      project folder, so the app and seed_db.py share the same file.
    """
    url = os.environ.get("DATABASE_URL")
    if url:
        if url.startswith("postgres://"):
            url = url.replace("postgres://", "postgresql://", 1)
        # Use the psycopg2 driver (the one in requirements.txt), so local and
        # Render behave the same regardless of SQLAlchemy's default.
        if url.startswith("postgresql://"):
            url = url.replace("postgresql://", "postgresql+psycopg2://", 1)
        return url
    return "sqlite:///" + os.path.abspath("quiz.db")


def init_quiz(app):
    """Wire the database and the quiz routes into your existing Flask app."""
    app.config["SQLALCHEMY_DATABASE_URI"] = database_uri()
    app.config.setdefault("SQLALCHEMY_TRACK_MODIFICATIONS", False)
    db.init_app(app)
    with app.app_context():
        db.create_all()          # make sure the table exists (safe to call every time)
    app.register_blueprint(quiz_bp)