"""
Week 7 — Database seeder (provided). Run this ONCE to fill the database with
the quiz questions. You do NOT edit this file.

RUN IT:
  - Locally (fills the local SQLite file quiz.db):
        python seed_db.py
  - Against your Render database (fills the PostgreSQL database):
        set the DATABASE_URL environment variable to your database's EXTERNAL URL,
        then run:  python seed_db.py

It creates the table if needed and inserts the questions only if the table is empty,
so it is safe to run more than once.
"""

import json
from flask import Flask
from quiz_api import db, Question, database_uri



QUESTIONS = [
    {
        "question": "Which keyword declares a block-scoped variable that can later be reassigned?",
        "choices": ["var", "let", "const", "def"],
        "answer": 1,
        "explanation": " let declares a block-scoped variable whose value may later be reassigned.",
    },
    {
        "question": "Which operator tests strict equality (value AND type)?",
        "choices": ["=", "==", "===", "!="],
        "answer": 2,
        "explanation": "=== compares both value and type.",
    },
    {
        "question": "What does JSON.parse() do?",
        "choices": [
            "Converts an object to text",
            "Converts JSON text into a JavaScript value",
            "Downloads a file",
            "Validates a form",
        ],
        "answer": 1,
        "explanation": "JSON.parse turns a JSON string into a JavaScript object/value.",
    },
    {
        "question": "Which array method creates a new array by transforming each element?",
        "choices": ["forEach", "map", "filter", "reduce"],
        "answer": 1,
        "explanation": "map returns a new array of transformed values.",
    },
    {
        "question": "What does the await keyword do?",
        "choices": [
            "Pauses the whole browser",
            "Waits for a promise to settle inside an async function",
            "Creates a new thread",
            "Declares a variable",
        ],
        "answer": 1,
        "explanation": "await waits for a promise to resolve/reject inside an async function.",
    },
    {
        "question": "After const r = await fetch(url), how do you read the JSON body?",
        "choices": ["r.body", "await r.json()", "JSON.parse(r)", "r.text"],
        "answer": 1,
        "explanation": "response.json() returns a promise, so you await it.",
    },
    {
        "question": "Does fetch() reject the promise on an HTTP 404 response?",
        "choices": [
            "Yes, 404 throws automatically",
            "No, you must check response.ok yourself",
            "Only in Firefox",
            "Only for POST requests",
        ],
        "answer": 1,
        "explanation": "fetch only rejects on network errors; check response.ok for HTTP errors.",
    },
    {
        "question": "Which block handles errors from an awaited fetch?",
        "choices": ["if/else", "try/catch", "switch", "for"],
        "answer": 1,
        "explanation": "try/catch catches errors thrown by awaited promises.",
    },
]


# A minimal app just for seeding (separate from your web app).
app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = database_uri()
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db.init_app(app)

with app.app_context():
    db.create_all()
    if Question.query.count() == 0:
        for q in QUESTIONS:
            db.session.add(
                Question(
                    question=q["question"],
                    choices=json.dumps(q["choices"]),
                    answer=q["answer"],
                    explanation=q["explanation"],
                )
            )
        db.session.commit()
        print("Seeded", len(QUESTIONS), "questions into", database_uri())
    else:
        print("Already seeded:", Question.query.count(), "questions.")